### ISSUE TITLE
Responsive / mobile support?

### ISSUE THREAD

**Issue by hartwork** [ingwinlu/pelican-twitchy#17]
Hi!

The docs don't say anything about responsiveness / mobile support. It would be cool to have that covered. Thank you!

**Comment by ingwinlu** [comment]
4 years late, but here goes: The responsiveness is provided by the underlying bootstrap framework.
However: since I am not really a webdeveloper looking back: I did some things wrong with regards to mobile first -> hence the mobile page score on things like google lighthouse pretty much is capped at ~85ish.
