### ISSUE TITLE
make html fails

### ISSUE THREAD

**Issue by eamonnfaherty** [ingwinlu/pelican-twitchy#4]
I am running make html and I get the following error:

CRITICAL: slice indices must be integers or None or have an __index__ method

**Comment by ingwinlu** [comment]
hey,

sorry for the delay;
can you provide more information, try running pelican with the -D flag and your full configuration else I can't help you

**Comment by shanpy** [comment]
I got the same issue. After comparing my `pelicanconf.py` and yours, which is https://github.com/ingwinlu/www.heroicdebugging.biz/blob/master/pelicanconf.py, I realized this line cause the problem:

`DISPLAY_RECENT_POSTS_ON_MENU = True`

You have to set this to `True` and make sure it is in you setting file. Otherwise when you do `make html`, you will get following error message:
`CRITICAL: slice indices must be integers or None or have an __index__ method`.

Hope this is useful for you :)

**Comment by ingwinlu** [comment]
not really, but I had a few minutes to look at it now.

I broke it with bbccea41b9abc1a5bd7865a67c5a359644d4a896.

I also just pushed 1.1.4 which should resolve the issue

**Comment by ingwinlu** [comment]
@eamonnfaherty @shanpy can I close this, or is this issue still around?

**Comment by eamonnfaherty** [comment]
works for me now.

Thanks a million!

**Comment by shanpy** [comment]
Solved my problem. Thank you!
